### ISSUE TITLE
Inbox with response mode=wait reports wave of same tracked requests

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [fanout/webhookinbox#14]
Step to reproduce:
* create new inbox with response_mode=wait
* open inbox dashboard in browser (http://webhookinbox.com/view/i27UwPuf/) to track new requests online
* use browser or postman to call the inbox URL ONCE (like http://api.webhookinbox.com/i/i27UwPuf/in/)

Expected: only one request displayed in inbox dashboard.
What is got: Inbox dashboard shows new requests comes again and again and those are THE SAME single request we sent in 3rd step above.

**Comment by jkarneges** [comment]
Thanks for the report! It seems there was a regression in one of the dependencies (Pushpin), which is causing this crazy behavior. Will fix this shortly.

**Comment by jkarneges** [comment]
This should be working correctly now.
