### ISSUE TITLE
Respond with empty body do not respond back to client

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [fanout/webhookinbox#15]
Steps to repro:
* create new inbox with respond_mode=wait and send there a test request. The client here is awaiting for response.
* respond back to the client with POST /i/{inbox}/respond/{request_id}/
   { "code":"200", "body":"" }

The respond call finished with 200/OK but initial client request didn't finish (will end up with 503).
Temp fix here: pass "body":" " (notice space instead of "")

**Comment by jkarneges** [comment]
Thanks for the report. This is now fixed.
