### ISSUE TITLE
http://webhookinbox.com/ not operating

### ISSUE THREAD

**Issue by PascalRiekenberg** [fanout/webhookinbox#19]
http://webhookinbox.com/ is not operating.
When you press "create inbox" nothing happens. Maybe the redis-server is not available.

**Comment by jkarneges** [comment]
Thanks for the report. It's fixed now.

**Comment by PascalRiekenberg** [comment]
Sorry to bother you again. I just did a test and it didn't create an inbox, just spinning forever.

**Comment by jkarneges** [comment]
Is it still not working? It was fine for me just now.

**Comment by PascalRiekenberg** [comment]
Yes, it does not work. Which browser are you using? I use Firefox 70.0.1 on Windows 10 1909.

**Comment by jkarneges** [comment]
Firefox 70.0.1 on Ubuntu 18.04.3.

I wonder if it's a network issue. In the network log, do you see an error making a request to api.webhookinbox.com?

You could also try curl:

```
curl -v -X POST https://api.webhookinbox.com/create/
```

**Comment by PascalRiekenberg** [comment]
curl is okay. an inbox is created.

Here is the weblog:

Pollymer 1 created WebhookInboxViewer.d0489eb6beb6.js:13:21
Pollymer 1> start (POST) WebhookInboxViewer.d0489eb6beb6.js:22:29
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 1229ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 2961ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 4058ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 8532ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 16033ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 32700ms pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: Using XHR transport. pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR start //api.webhookinbox.com/create/ pollymer-1.1.1.ba0624a4f4c6.js:32:44
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://api.webhookinbox.com/create/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

pollymer: XHR finished pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: XHR cleanup pollymer-1.1.1.ba0624a4f4c6.js:32:44
pollymer: trying again in 64805ms pollymer-1.1.1.ba0624a4f4c6.js:32:44

**Comment by PascalRiekenberg** [comment]
Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt
-> Reason: CORS-Header 'Access-Control-Allow-Origin' missing

**Comment by jkarneges** [comment]
Weird. The header is being sent. I see it in the curl response, and in the Firefox network log:

![Screenshot from 2019-11-22 07-32-34](https://user-images.githubusercontent.com/521953/69438750-760ad480-0cfa-11ea-8b1a-6c83b89041db.png)

Are you using any FF add-ons/proxies that might be filtering traffic?

**Comment by SuS-PascalR** [comment]
This is still an issue on recent Firefox/Edge.

**Comment by SuS-PascalR** [comment]
Just enter "webhookinbox.com", press enter and klick on "create an inbox". Nothing seems to happen. Press F12 and see "Console"-Tab for error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.webhookinbox.com/create/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

**Comment by jkarneges** [comment]
The header is there:

<img width="549" alt="Screenshot 2023-08-16 at 10 04 10 AM" src="https://github.com/fanout/webhookinbox/assets/521953/f33dedc3-8350-4bc6-a699-80ada0a792f6">

I wonder if you have a proxy messing with the request.

**Comment by SuS-PascalR** [comment]
You are right, this might be our firewall. If i use it at home without vpn everything works as expected. Sorry for the noise.
