### ISSUE TITLE
Dockerfile, feature request.

### ISSUE THREAD

**Issue by josenk** [fanout/webhookinbox#20]
Any plans to provide a Dockerfile for this tool?

   I did a quick attempt to do it.  However, when I click "Create an Inbox", it just spins.   tcpdump doesn't really show any activity on any interface on-click.   I suspect context paths or ports that could be causing the issue.   Any help would be appreciated to help debug this...

**Comment by jkarneges** [comment]
Maybe a CORS issue. Anything in the browser logs?

**Comment by josenk** [comment]
I did a little more debugging today with the browser in developer mode.

    When I click "Create an Inbox", it tries to connect to http://localhost:7999/api/create/.  (I have docker running locally, so the localhost part is correct).  I see it's trying to use the pushpin port (7999), which I don't have "EXPOSED" in docker.   Looking at all the required ports for pushpin, I'm starting to believe this might not be easily ported to Docker.

  My ideal deployed configuration would be to have two or three docker containers running behind a load-balancer and a single Redis (elasticache).  Is there a way to get this working with a single entry port (8000)?

**Comment by jkarneges** [comment]
Ah, the browser should be connecting to the front pushpin port (7999 by default). It's the only port you should need from the client side. Pushpin will proxy to the backend API.

**Comment by jkarneges** [comment]
Relatedly, you'll want to set `WHINBOX_API_BASE` to a proper value. The URL there is what is given to the browser JS code for making API calls.
