### ISSUE TITLE
HTTP response 308 Permanent Redirect when interacting with the WebhookInbox API

### ISSUE THREAD

**Issue by DavidWoodwardatSage** [fanout/webhookinbox#54]
1. Attempt to create an inbox via a POST to POST http://api.webhookinbox.com/create/ with body...

 id=testabc
 
 Response...
 
 HTTP/1.1 308 Permanent Redirect
Content-length: 0
Location: https://api.webhookinbox.com/create/
Connection: close

**Comment by DavidWoodwardatSage** [comment]
The 308 error is also occurring on other GET requests such as GET http://api.webhookinbox.com/i/Jakdfjk/items/?order=-created&since=&max=1

**Comment by jkarneges** [comment]
Yes, `api.webhookinbox.com` now requires https.

**Comment by DavidWoodwardatSage** [comment]
Thanks, I've confirmed that is now working with the change
