### ISSUE TITLE
Can't create WebhookInbox through webpage

### ISSUE THREAD

**Issue by conor-carville** [fanout/webhookinbox#56]
Go to http://webhookinbox.com/
    Click create an inbox (alternatively attempt via the API)

Observed behaviour
Web page - 'Creating' spinner displays indefinitely.
API - 200 OK and inbox is created

**Comment by jkarneges** [comment]
API calls are lagging and sometimes failing. The create button worked for me just now but probably luck. Will look into it.

**Comment by jkarneges** [comment]
This appears to be resolved.

**Comment by conor-carville** [comment]
We are still seeing issues on both the ui and through the api can this please be investigated again?

**Comment by jkarneges** [comment]
The service has been upgraded to help with this. We don't actually know why we were having issues, but old packages were making it hard to debug. Things look okay right now, and if issues arise again it should be easier to investigate.
