### ISSUE TITLE
http://webhookinbox.com/ The page isn't working response

### ISSUE THREAD

**Issue by DavidWoodwardatSage** [fanout/webhookinbox#57]
1. go to webhookinbox.com

Observed behaviuor...

This page isn’t workingwebhookinbox.com didn’t send any data.
ERR_EMPTY_RESPONSE

Note: Performance of the API has degraded significantly over the last few weeks.

**Comment by jkarneges** [comment]
Yeah, we still don't know what's up with that, but in the meantime we've upgraded the service. Old packages were making it hard to debug. Seems to be working okay now.
