### ISSUE TITLE
https://webhookinbox.com/ - Internal Server Error

### ISSUE THREAD

**Issue by DavidWoodwardatSage** [fanout/webhookinbox#63]
https://webhookinbox.com/ gives Internal Server Error response.

**Comment by jkarneges** [comment]
It should be back online now.

**Comment by DavidWoodwardatSage** [comment]
@jkarneges  Still the same this morning, sorry.

**Comment by jkarneges** [comment]
Hopefully better now.

**Comment by DavidWoodwardatSage** [comment]
Yes thanks, All is back to normal and working perfectly.
